window.NEWS=[
{f:"2026-08-28",org:"DGT",tipo:"Listado oficial",t:"Actualización del listado de marcas y modelos V16 certificados",r:"La DGT actualiza la página oficial de dispositivos de preseñalización V16, con los listados de modelos certificados y de certificados con vigencia finalizada. Los certificados finalizados siguen siendo válidos para quien compró la baliza, hasta el fin de su vida útil.",u:"https://www.dgt.es/muevete-con-seguridad/tecnologia-e-innovacion-en-carretera/Dispositivos-de-presenalizacion-V16/"},
{f:"2026-07-09",org:"DGT",tipo:"Plataforma",t:"DGT 3.0: cómo se valida y publica una baliza V16 activada",r:"Al activarse, la V16 transmite su ubicación a DGT 3.0. La plataforma la contrasta con los sistemas de gestión de tráfico y, si confirma el incidente, lo publica para alertar a los conductores cercanos.",u:"https://www.dgt.es/muevete-con-seguridad/tecnologia-e-innovacion-en-carretera/dgt-3.0/"},
{f:"2025-11-25",org:"DGT",tipo:"Nota de prensa",t:"DGT recuerda la obligación de disponer de la baliza V-16 para señalizar averías y accidentes en carretera",r:"Desde el 1 de enero de 2026 la V-16 conectada es el único medio legal de señalización y no llevarla se sanciona con 80 euros. La conectividad está incluida en el precio durante al menos 12 años y los datos son anónimos.",u:"https://www.dgt.es/comunicacion/notas-de-prensa/20251125-dgt-recuerda-la-obligacion-de-disponer-de-la-baliza-v-16-para-senalizar-averias-y-accidentes-en-carretera/"},
{f:"2025-11-25",org:"La Moncloa · Interior",tipo:"Nota de prensa",t:"Baliza V16 conectada: qué es, para qué sirve y cuándo será obligatoria",r:"Nota del Gobierno sobre la obligatoriedad de la baliza V16 conectada, que sustituye a los triángulos desde el 1 de enero de 2026.",u:"https://www.lamoncloa.gob.es/serviciosdeprensa/notasprensa/interior/paginas/2025/251125-obligacion-baliza-v16-carretera.aspx"},
{f:"2025-10-15",org:"Revista DGT",tipo:"Reportaje",t:"La V16 conectada en 20 preguntas",r:"Guía oficial: la baliza solo transmite su posición cuando se activa, no envía datos personales ni del vehículo, y no necesita móvil, registro ni cuotas.",u:"https://revista.dgt.es/es/reportajes/2025/10OCTUBRE/1015-N275-20Preguntas_V16conectada.shtml"},
{f:"2025-01-24",org:"DGT",tipo:"Instrucción",t:"Tráfico publica una instrucción para aclarar el uso de la señal V-16 en la circulación internacional",r:"Instrucción MOV 2025/1 sobre la V-16 en vehículos matriculados en otros países que circulan por España.",u:"https://www.dgt.es/comunicacion/notas-de-prensa/20250124-trafico-publica-instruccion-usos-v-16-en-circulacion-internacional/"},
{f:"2022-12-21",org:"BOE",tipo:"Normativa",t:"Real Decreto 1030/2022, que modifica el Real Decreto 159/2021",r:"Fija la transición de las V-16 sin conexión hasta el 1 de enero de 2026 y obliga a indicar en el envase y en el dispositivo la fecha en que caduca la conectividad.",u:"https://www.boe.es/buscar/doc.php?id=BOE-A-2022-21683"},
{f:"2021-12-10",org:"BOE · DGT",tipo:"Normativa",t:"Resolución de 30 de noviembre de 2021: protocolo de envío de datos de la señal V-16",r:"Define el protocolo: primer mensaje a los 100 segundos del encendido y después uno cada 100 segundos, red 4G/5G LPWA, SIM no extraíble y 12 años de conectividad prepagada.",u:"https://www.boe.es/diario_boe/txt.php?id=BOE-A-2021-20433"},
{f:"2021-03-16",org:"BOE",tipo:"Normativa",t:"Real Decreto 159/2021, por el que se regulan los servicios de auxilio en las vías públicas",r:"Norma base que crea la señal V-16 de preseñalización de peligro y su conexión con la DGT.",u:"https://www.boe.es/buscar/act.php?id=BOE-A-2021-4194"}
];
